### ISSUE TITLE
Display error if images _aren't_ indexed

### ISSUE THREAD

**Issue by dmrickey** [manuel-hegner/foundry-filepicker-favorites#20]
Is it possible to suppress the ui popup that shows up when the images are done indexing? I assume that mods are working unless they say otherwise. I don't personally have any need for the ui notification saying that "the thing" did "what it was supposed to". Also some of my players constantly warn me whenever anything pops up on their screen that they didn't prompt. 

So my suggestion is to pop up a notification if the index fails, and to move the current message to the console. If you could do that it would be much appreciated.

**Comment by manuel-hegner** [comment]
Logging the default message only in the console seems sensible. I'll do it like that.

**Comment by dmrickey** [comment]
Awesome, thanks.. random question.. so you know how much memory it takes to store that index? Is it's significant, I wonder if it might be prudent to not index until the file picker is opened the first time. Like, my players never interact with the file picker, and during a regular game session I never do either--only during prep

**Comment by manuel-hegner** [comment]
The memory consumption fully depends on how much images are visible to foundry. For me it is 31MB with 120k images.

It should not have any impact on your players if they do not have the "Use File Browser" permission.
Indexing only on opening the browser will not work well I am afraid since it can be a very slow thing. Especially if you store pictures remotely (e.g. on the forge).
